---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-server
  user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mysql 
    - nginx
    - php-fpm
    - wordpress
